//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace приложение.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public int ClassID { get; set; }
        public string Description { get; set; }
    
        public virtual Classes Classes { get; set; }
        public virtual Teachers Teachers { get; set; }
    }
}
